apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app"
  annotations:
    argocd/app-name: my-quarkus-app-dev
    backstage.io/kubernetes-id: my-quarkus-app
    github.com/project-slug: 9strands-testing-organization/backstage-sample-quarkus-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-llp4s.llp4s.sandbox1995.opentlc.com/#https://github.com/9strands-testing-organization/backstage-sample-quarkus-app?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-llp4s.llp4s.sandbox1995.opentlc.com/#https://github.com/9strands-testing-organization/backstage-sample-quarkus-app?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "Quarkus-Team"
  providesApis:
    - "my-quarkus-app"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app"
spec:
  type: openapi
  lifecycle: production
  owner: "Quarkus-Team"
  definition:
    $text: ./openapi.yaml